CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- NOW()
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- NOW()
);
