CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL CHECK(LENGTH(TRIM(name)) > 0),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- NOW()
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- NOW()
);
